### ISSUE TITLE
Easier installation instructions for README.md

### ISSUE THREAD

**Issue by gmlewis** [skanehira/gjo#12]
Very cool tool... thank you very much!

I think your installation instructions could be easier... this worked for me:

```
$ go get github.com/skanehira/gjo
$ which gjo
/home/glenn/go/bin/gjo
$ gjo one=two three=$(gjo -a 1 2 3)
{"one":"two","three":[1,2,3]}
```

**Comment by skanehira** [comment]
Thank you for using :)

`gjo` have no any dependency, so you can use `go get`.
However, I may recommend `go install` because there may be dependencies in the future.
